# docker-compose.yml
version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=nestjs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongodb_data: